#!/bin/bash
#
# Rebuild via workflows
#
# Required environment variables:
#   GH_TOKEN - required repository permissions for "Actions"
#   DIUN_ENTRY_IMAGE - https://crazymax.dev/diun/notif/script/
#

set -euo pipefail

workflows="$(
  curl -L \
  -X "GET" \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ${GH_TOKEN}" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "https://api.github.com/repos/hkcomori/dockerfiles/actions/workflows"
)"

rebuild() {
  workflow_name="$(basename "$1")"
  workflow_url="$(
    echo "${workflows}" \
    | jq ".workflows[] | select(.name == \"${workflow_name}\") | .url"
  )"
  curl -L \
  -X "POST" \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ${GH_TOKEN}" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "${workflow_url}/dispatches"\
  -d "{\"ref\": \"main\"}"
}

case "${DIUN_ENTRY_IMAGE}" in
  docker.io/library/ubuntu:latest )
    rebuild postfix
    ;;

  docker.io/library/debian:12-slim )
    rebuild github-cli
    ;;

  certbot/certbot:latest )
    rebuild certbot
    ;;

  gcr.io/distroless/static-debian12 )
    rebuild privoxy
    ;;

  gcr.io/distroless/nodejs20-debian12 )
    rebuild w3cli
    ;;
esac
