name: privoxy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'privoxy/**'

jobs:
  publish_to_ghcr:
    uses: ./.github/workflows/ghcr_publish.yml
    with:
      description: "Privoxy distroless image"
      path: ${{ github.workflow }}
      revision: ${{ github.sha }}
      username: ${{ github.actor }}
    secrets:
      password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      packages: write
