name: privoxy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'privoxy/**'

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        run: |
          cd $GITHUB_WORKFLOW
          docker build \
          --tag ghcr.io/$GITHUB_ACTOR/$GITHUB_WORKFLOW:latest \
          --tag ghcr.io/$GITHUB_ACTOR/$GITHUB_WORKFLOW:$(echo $GITHUB_SHA | head -c7) \
          .
      - name: Push Docker Image
        run: |
          docker push ghcr.io/$GITHUB_ACTOR/$GITHUB_WORKFLOW:latest
          docker push ghcr.io/$GITHUB_ACTOR/$GITHUB_WORKFLOW:$(echo $GITHUB_SHA | head -c7)
